name: activate
on:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: date --iso-8601=seconds --utc > .activation
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Activate
          
