name: activate
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update file
        run: date --iso-8601=seconds --utc > .activation
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Activate
