name: nextdns
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:
env:
  NEXTDNS_API_KEY: ${{secrets.NEXTDNS_API_KEY}}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release -- update --source ${{ secrets.NEXTDNS_SOURCE_URL }} --profile ${{ secrets.NEXTDNS_PROFILE_ID }} --force
