name: nextdns
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"
env:
  NEXTDNS_API_KEY: ${{secrets.NEXTDNS_API_KEY}}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ secrets.NEXTDNS_GITHUB_REPOSITORY }}
          token: ${{ secrets.NEXTDNS_GITHUB_PAT }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release -- update --source ${{ secrets.NEXTDNS_SOURCE_URL }} --profile ${{ secrets.NEXTDNS_PROFILE_ID }} --force
