name: update-feeds
on:
  schedule:
    - cron: "*/10 * * * *"
env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.FEED_GOOGLE_APPLICATION_CREDENTIALS}}
  GOOGLE_CLOUD_STRORAGE_BUCKET: ${{secrets.FEED_GOOGLE_CLOUD_STRORAGE_BUCKET}}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.FEED_GITHUB_REPOSITORY }}
          token: ${{ secrets.FEED_GITHUB_PAT }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Update feeds
        run: yarn run update-feeds
